"""Inspect source + regen rlog pair: versions, frameId alignment, route timing.

Tells us whether the pair is usable for Step 3.5 parity:
- source rlog should carry roadCameraState/roadEncodeIdx tying fcamera.hevc -> frameId
- regen rlog should carry modelV2 events with frameIds matching source camera frames
- regen must have been generated by v0.9.7 modeld for the parity check to be meaningful
"""

from __future__ import annotations

import sys
from collections import Counter
from pathlib import Path

import capnp

from src.rlog import iter_events

DATA = Path(__file__).resolve().parents[1] / "data"
SOURCE_RLOG = DATA / "source" / "rlog.bz2"
REGEN_RLOG = DATA / "regen" / "rlog.bz2"


def scan(rlog_path: Path, label: str) -> dict:
    print(f"\n=== {label}: {rlog_path.name} ===")
    types = Counter()
    init_version = None
    init_dirty = None
    model_v2_frame_ids = []
    road_cam_frame_ids = []
    road_encode_idx = []
    log_mono_times = {"min": None, "max": None}
    first_modelv2 = None

    for ev in iter_events(rlog_path):
        try:
            which = ev.which()
        except capnp.KjException:
            continue
        types[which] += 1
        ts = ev.logMonoTime
        if log_mono_times["min"] is None or ts < log_mono_times["min"]:
            log_mono_times["min"] = ts
        if log_mono_times["max"] is None or ts > log_mono_times["max"]:
            log_mono_times["max"] = ts

        if which == "initData":
            init_version = ev.initData.version
            init_dirty = ev.initData.dirty
        elif which == "modelV2":
            mv = ev.modelV2
            model_v2_frame_ids.append(mv.frameId)
            if first_modelv2 is None:
                first_modelv2 = {
                    "frameId": mv.frameId,
                    "timestampEof": mv.timestampEof,
                    "accel_x0": list(mv.acceleration.x)[:1],
                    "accel_x_len": len(mv.acceleration.x),
                    "logMonoTime": ts,
                }
        elif which == "roadCameraState":
            rcs = ev.roadCameraState
            road_cam_frame_ids.append(rcs.frameId)
        elif which == "roadEncodeIdx":
            ri = ev.roadEncodeIdx
            road_encode_idx.append((ri.frameId, ri.segmentNum if hasattr(ri, "segmentNum") else None))

    print(f"  events       : {sum(types.values())}")
    print(f"  duration     : {(log_mono_times['max'] - log_mono_times['min']) / 1e9:.2f} s "
          f"(monotonic clock)")
    print(f"  initData.version : {init_version!r}")
    print(f"  initData.dirty   : {init_dirty}")
    print(f"  modelV2 events   : {len(model_v2_frame_ids)} "
          f"(frameId range {min(model_v2_frame_ids) if model_v2_frame_ids else '-'}..{max(model_v2_frame_ids) if model_v2_frame_ids else '-'})")
    print(f"  roadCameraState  : {len(road_cam_frame_ids)} "
          f"(frameId range {min(road_cam_frame_ids) if road_cam_frame_ids else '-'}..{max(road_cam_frame_ids) if road_cam_frame_ids else '-'})")
    print(f"  roadEncodeIdx    : {len(road_encode_idx)}")
    if first_modelv2:
        print(f"  first modelV2    : frameId={first_modelv2['frameId']}, "
              f"accel.x[0]={first_modelv2['accel_x0']}, "
              f"accel.x len={first_modelv2['accel_x_len']}")
    # show top non-zero event types
    print(f"  top event types  : {types.most_common(8)}")
    return {
        "version": init_version,
        "model_v2_frame_ids": set(model_v2_frame_ids),
        "road_cam_frame_ids": set(road_cam_frame_ids),
    }


def main() -> int:
    source = scan(SOURCE_RLOG, "SOURCE")
    regen = scan(REGEN_RLOG, "REGEN")

    print("\n=== ALIGNMENT ===")
    src_ids = source["road_cam_frame_ids"]
    reg_ids = regen["model_v2_frame_ids"]
    print(f"  source roadCameraState frameIds: {len(src_ids)}")
    print(f"  regen  modelV2          frameIds: {len(reg_ids)}")
    if src_ids and reg_ids:
        overlap = src_ids & reg_ids
        print(f"  intersection                    : {len(overlap)} "
              f"({100 * len(overlap) / max(len(src_ids), len(reg_ids)):.1f}% of larger set)")
        if overlap:
            print(f"  overlap range                   : {min(overlap)}..{max(overlap)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
